# Generated by Django 5.2.16 on 2026-07-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_newstranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestReview',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('news_id', models.IntegerField()),
                ('decision', models.CharField(max_length=16)),
                ('score', models.FloatField(null=True)),
                ('reason', models.TextField()),
                ('selector_name', models.CharField(max_length=200)),
                ('selector_version', models.CharField(max_length=200)),
                ('idempotency_key', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'exchange_latest_reviews',
                'managed': False,
            },
        ),
    ]
