# Generated by Django 5.2.16 on 2026-07-25 20:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


# One object for the pipeline to read: the thresholds in force, with the name
# and revision that identify them in `selector_version`.
FORWARD_SQL = """
CREATE VIEW exchange_active_selection_profile AS
SELECT
    p.name AS profile_name,
    p.revision AS profile_revision,
    b.characteristic_key,
    b.kind,
    b.value
FROM exchange_selection_profile p
JOIN exchange_selection_bound b ON b.profile_id = p.id
WHERE p.is_active = 1;
"""

REVERSE_SQL = """
DROP VIEW IF EXISTS exchange_active_selection_profile;
"""

# The owner's rule, until now hard-coded in pipeline/evaluator.py as
# DEFAULT_PROFILE. Strict on purpose: few items pass. heroism is an upper gate
# here even though its reference threshold_direction is lower_bound.
DEFAULT_BOUNDS = (
    [("positivity", "gate_min", 8)]
    + [(key, "gate_max", 4) for key in ("heroism", "clickbait", "promo")]
    + [(key, "highlight_min", 9) for key in (
        "pride_humanity", "pride_russia", "inspiration", "beauty",
        "interestingness", "surprise", "uniqueness",
    )]
)


def seed_default_profile(apps, schema_editor):
    profile_model = apps.get_model("collector", "SelectionProfile")
    bound_model = apps.get_model("collector", "SelectionBound")
    profile, _ = profile_model.objects.update_or_create(
        name="default",
        defaults={
            "is_active": True,
            "revision": 1,
            "note": "Правило владельца: строгий отбор, проходят единицы.",
        },
    )
    for key, kind, value in DEFAULT_BOUNDS:
        bound_model.objects.update_or_create(
            profile=profile, characteristic_id=key, kind=kind, defaults={"value": value}
        )


def unseed_default_profile(apps, schema_editor):
    apps.get_model("collector", "SelectionProfile").objects.filter(name="default").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_latestreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exchange_selection_profile',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uq_one_active_selection_profile')],
            },
        ),
        migrations.CreateModel(
            name='SelectionBound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gate_min', 'Обязательное: не ниже'), ('gate_max', 'Обязательное: не выше'), ('highlight_min', 'Сильная сторона: не ниже')], max_length=16)),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('characteristic', models.ForeignKey(db_column='characteristic_key', on_delete=django.db.models.deletion.PROTECT, related_name='selection_bounds', to='collector.evaluationcharacteristic', to_field='key')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounds', to='collector.selectionprofile')),
            ],
            options={
                'db_table': 'exchange_selection_bound',
                'ordering': ['kind', 'characteristic_id'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'characteristic', 'kind'), name='uq_selection_bound'), models.CheckConstraint(condition=models.Q(('value__gte', 0), ('value__lte', 10)), name='ck_selection_bound_range')],
            },
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
        migrations.RunPython(seed_default_profile, unseed_default_profile),
    ]
