# Generated by Django 5.2.16 on 2026-07-25 21:59

import django.db.models.deletion
from django.db import migrations, models


# The order the publisher should take prepared news in, and the operator's edits
# to it. «Сила» is a weighted sum of the axes: half the best strong side, then
# positivity and interestingness. Preparation time — what the publisher used
# before this view — says when the machine got round to an item, not how good it
# is, so a strong evening story went out at night behind three average ones.
#
# The weights live in SQL because the pipeline must be able to read the finished
# number: it may read views, and computing this on its side would be a second
# copy of a rule that already exists in the operator UI.
FORWARD_SQL = """
CREATE VIEW exchange_publication_order AS
SELECT
    s.news_id,
    ROUND(
        0.5 * MAX(CASE WHEN s.characteristic_key IN (
                    'pride_humanity', 'pride_russia', 'inspiration', 'beauty',
                    'interestingness', 'surprise', 'uniqueness'
                 ) THEN s.value ELSE 0 END)
      + 0.3 * MAX(CASE WHEN s.characteristic_key = 'positivity' THEN s.value ELSE 0 END)
      + 0.2 * MAX(CASE WHEN s.characteristic_key = 'interestingness' THEN s.value ELSE 0 END),
    2) AS strength,
    COALESCE(p.rank, 0) AS operator_rank,
    p.hold_until AS hold_until,
    p.dropped_at AS dropped_at
FROM exchange_latest_evaluation_scores s
LEFT JOIN exchange_publication_plan p ON p.news_id = s.news_id
WHERE s.selector_name = 'news-evaluator'
GROUP BY s.news_id;
"""

REVERSE_SQL = """
DROP VIEW IF EXISTS exchange_publication_order;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_selection_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0, help_text='Ниже — раньше. 0 значит «как решит порядок по силе».')),
                ('hold_until', models.DateTimeField(blank=True, null=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news_item', models.OneToOneField(db_column='news_id', on_delete=django.db.models.deletion.CASCADE, related_name='publication_plan', to='collector.newsitem')),
            ],
            options={
                'db_table': 'exchange_publication_plan',
                'ordering': ['rank', 'news_item_id'],
            },
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
