# Generated by Django 5.2.16 on 2026-07-29 21:33

from django.db import migrations, models

# The `day` slot as it worked in ~/repo/ort_bot (services/picture_of_day.py),
# adapted to the model router: the router has no web search, so the system
# prompt asks the model to build the day from its own knowledge of the calendar
# rather than from search results. Seeded switched OFF — nothing generates or
# publishes until the operator enables it on the «Картина дня» page.
DAY_PROMPT = (
    "Подготовь промпт для модели генерации картинок, чтобы она сделала «картину дня»: "
    "отрази праздники и приметы именно этого дня, сезон и атмосферу, без текста и "
    "текстовых табличек на самой картинке. В списке праздников приоритет российским. "
    "Только внизу картинки — небольшая плашка шрифтом среднего размера, в том же стиле, "
    "что и вся картинка, с указанием на русском языке, какие сегодня праздники. "
    "Формат вертикальный. Переданный стиль возьми базовым стилем картинки и передай его "
    "в промпт."
)

DAY_SYSTEM_PROMPT = (
    "Ты готовишь безопасный и точный промпт для модели генерации изображений. "
    "Веб-поиска у тебя нет: опирайся на переданную дату и своё знание календаря — "
    "государственные, народные и международные праздники этого дня. Если день связан с "
    "конфликтными, трагическими или политически чувствительными событиями, не тащи их в "
    "визуал: оставь только нейтральное настроение дня, сезон, атмосферу и праздники. "
    "Отвечай одним готовым промптом на русском языке, без пояснений."
)

# One per line, picked by day of month: 31 styles, one for every possible day.
DAY_STYLES = "\n".join((
    "low-poly", "vaporwave", "surrealism", "3d-render", "atompunk",
    "fantasy-art", "isometric-art", "stained-glass", "realistic",
    "paper-cut-3d-layered-style", "minimalism", "art-deco", "ink-wash",
    "papercraft-diorama", "steampunk", "photographic", "embroidery",
    "pop-art", "mosaic", "claymation", "constructivist", "pointillism",
    "decopunk", "comic-book-style", "ukiyo-e", "ceramic-tile", "blueprint",
    "psychedelic-art", "ink-illustration", "chalkboard-art", "vintage-photo",
))


def seed_day_slot(apps, schema_editor):
    slot_model = apps.get_model("collector", "DaypicSlot")
    slot_model.objects.update_or_create(
        slot="day",
        defaults={
            "enabled": False,
            "title": "Картина дня",
            "generate_at": "08:00",
            "prompt": DAY_PROMPT,
            "system_prompt": DAY_SYSTEM_PROMPT,
            "styles": DAY_STYLES,
        },
    )


def unseed_day_slot(apps, schema_editor):
    apps.get_model("collector", "DaypicSlot").objects.filter(slot="day").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_news_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaypicSlot',
            fields=[
                ('slot', models.SlugField(max_length=32, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('title', models.CharField(default='Картина дня', max_length=200)),
                ('generate_at', models.CharField(default='08:00', max_length=5)),
                ('prompt', models.TextField()),
                ('system_prompt', models.TextField(blank=True)),
                ('styles', models.TextField(blank=True)),
                ('chat_provider', models.CharField(blank=True, max_length=100)),
                ('chat_model', models.CharField(blank=True, max_length=200)),
                ('image_provider', models.CharField(blank=True, max_length=100)),
                ('image_model', models.CharField(blank=True, max_length=200)),
                ('image_size', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exchange_daypic_slot',
                'ordering': ['slot'],
            },
        ),
        migrations.RunPython(seed_day_slot, unseed_day_slot),
    ]
