# Generated by Django 5.2.16 on 2026-07-29 21:58

from django.db import migrations, models

# The 0012 seed texts were written for one vertical picture and a plain-text
# answer. Both assumptions are gone: every issue is now drawn in two
# orientations from one prompt (so the prompt must not fix the frame), and the
# pipeline asks for JSON with the image prompt plus a Russian description of
# the day — the format instruction travels in the pipeline's request, so the
# system prompt must not demand «одним готовым промптом» any more. Only a slot
# whose texts still equal the 0012 seed is updated: an operator's edit wins.
OLD_PROMPT = (
    "Подготовь промпт для модели генерации картинок, чтобы она сделала «картину дня»: "
    "отрази праздники и приметы именно этого дня, сезон и атмосферу, без текста и "
    "текстовых табличек на самой картинке. В списке праздников приоритет российским. "
    "Только внизу картинки — небольшая плашка шрифтом среднего размера, в том же стиле, "
    "что и вся картинка, с указанием на русском языке, какие сегодня праздники. "
    "Формат вертикальный. Переданный стиль возьми базовым стилем картинки и передай его "
    "в промпт."
)

NEW_PROMPT = (
    "Подготовь промпт для модели генерации картинок, чтобы она сделала «картину дня»: "
    "отрази праздники и приметы именно этого дня, сезон и атмосферу, без текста и "
    "текстовых табличек на самой картинке. В списке праздников приоритет российским. "
    "Только внизу картинки — небольшая плашка шрифтом среднего размера, в том же стиле, "
    "что и вся картинка, с указанием на русском языке, какие сегодня праздники. "
    "Ориентацию кадра в промпте не задавай: картинка рисуется и вертикальной, и "
    "горизонтальной. Переданный стиль возьми базовым стилем картинки и передай его "
    "в промпт."
)

OLD_SYSTEM_PROMPT = (
    "Ты готовишь безопасный и точный промпт для модели генерации изображений. "
    "Веб-поиска у тебя нет: опирайся на переданную дату и своё знание календаря — "
    "государственные, народные и международные праздники этого дня. Если день связан с "
    "конфликтными, трагическими или политически чувствительными событиями, не тащи их в "
    "визуал: оставь только нейтральное настроение дня, сезон, атмосферу и праздники. "
    "Отвечай одним готовым промптом на русском языке, без пояснений."
)

NEW_SYSTEM_PROMPT = (
    "Ты готовишь безопасный и точный промпт для модели генерации изображений и короткое "
    "описание дня для подписи под картинкой. "
    "Веб-поиска у тебя нет: опирайся на переданную дату и своё знание календаря — "
    "государственные, народные и международные праздники этого дня. Если день связан с "
    "конфликтными, трагическими или политически чувствительными событиями, не тащи их в "
    "визуал и описание: оставь только нейтральное настроение дня, сезон, атмосферу и "
    "праздники. Промпт и описание пиши по-русски."
)


def refresh_day_seed(apps, schema_editor):
    slot_model = apps.get_model("collector", "DaypicSlot")
    slot_model.objects.filter(slot="day", prompt=OLD_PROMPT).update(prompt=NEW_PROMPT)
    slot_model.objects.filter(slot="day", system_prompt=OLD_SYSTEM_PROMPT).update(
        system_prompt=NEW_SYSTEM_PROMPT
    )


def restore_day_seed(apps, schema_editor):
    slot_model = apps.get_model("collector", "DaypicSlot")
    slot_model.objects.filter(slot="day", prompt=NEW_PROMPT).update(prompt=OLD_PROMPT)
    slot_model.objects.filter(slot="day", system_prompt=NEW_SYSTEM_PROMPT).update(
        system_prompt=OLD_SYSTEM_PROMPT
    )


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_daypicslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='daypicslot',
            name='image_size_wide',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(refresh_day_seed, restore_day_seed),
    ]
