# Generated by Django 5.2.16 on 2026-07-29 22:19

from django.db import migrations, models


# An empty size field means «the pipeline's default», which nobody can see from
# the page. Existing rows get the real numbers so the operator edits values,
# not blanks; the pipeline behaves the same either way.
def fill_empty_sizes(apps, schema_editor):
    slot_model = apps.get_model("collector", "DaypicSlot")
    slot_model.objects.filter(image_size="").update(image_size="1024x1536")
    slot_model.objects.filter(image_size_wide="").update(image_size_wide="1536x1024")


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_daypicslot_image_size_wide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daypicslot',
            name='image_size',
            field=models.CharField(blank=True, default='1024x1536', max_length=20),
        ),
        migrations.AlterField(
            model_name='daypicslot',
            name='image_size_wide',
            field=models.CharField(blank=True, default='1536x1024', max_length=20),
        ),
        migrations.RunPython(fill_empty_sizes, migrations.RunPython.noop),
    ]
